import { data } from "../package.json";

const { port } = data.input;

console.log(`# THIS FILE IS AUTOGENERATED; MANUAL CHANGES WILL BE OVERWRITTEN.
FROM --platform=linux/amd64 node:lts-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN yarn install --production --silent && mv node_modules ../
COPY . .
EXPOSE ${port}
RUN chown -R node /usr/src/app
USER node
CMD ["yarn", "serve"]`);
